### ISSUE TITLE
How do I run the examples?

### ISSUE THREAD

**Issue by elorest** [l3kn/raytracer-crystal#1]
How do I run these? I compile and run them but nothing happens.

**Comment by l3kn** [comment]
If you run `crystal run --release scenes/benchmark_scene.cr`it should create
a .ppm file in your current directory.

I'm going to put more instructions on how to use this in the readme
once things are more stable.

**Comment by elorest** [comment]
Thanks.

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005
