### ISSUE TITLE
Update for latest crystal

### ISSUE THREAD

**Issue by crisward** [l3kn/raytracer-crystal#3]
Just tried these with crystal 0.22 and they don't appear to work.
Any plans to update? BTW images looks very cool.

**Comment by l3kn** [comment]
Thanks!

I'm working on some big changes in the [BxDF Branch](https://github.com/l3kn/raytracer/tree/BxDF) (which seems to work with 0.22.0),
so the code on master is quite old.

If you want to play around with the code, please use the versions on the BxDF branch,
I'll merge in the next few days. Let me now if you run into any other issues
or something is unclear, the documentations is not as good as I'd like it to be.

**Comment by l3kn** [comment]
Everything is merged into master now
and seems to work with crystal 0.23.0
